// Drizzle table definitions live here.
// Better Auth tables are generated by `pnpm auth:generate`; don't edit auth-schema.ts by hand.
import { relations, sql } from "drizzle-orm";
import {
  check,
  index,
  integer,
  jsonb,
  pgEnum,
  pgTable,
  primaryKey,
  text,
  timestamp,
  uuid,
} from "drizzle-orm/pg-core";

import { user } from "./auth-schema";

const timestamps = {
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true })
    .notNull()
    .defaultNow()
    .$onUpdate(() => new Date()),
};

export const categories = pgTable("categories", {
  id: integer("id").primaryKey().generatedAlwaysAsIdentity(),
  slug: text("slug").notNull().unique(),
  name: text("name").notNull(),
  nameZh: text("name_zh").notNull(),
  blurb: text("blurb").notNull(),
  imageUrl: text("image_url").notNull(),
  imageAlt: text("image_alt").notNull(),
  /** Display order; the first category leads the homepage collections grid. */
  sortOrder: integer("sort_order").notNull().default(0),
  ...timestamps,
});

export const productBadge = pgEnum("product_badge", ["New", "Limited", "Bestseller"]);

export const products = pgTable(
  "products",
  {
    id: integer("id").primaryKey().generatedAlwaysAsIdentity(),
    slug: text("slug").notNull().unique(),
    categoryId: integer("category_id")
      .notNull()
      .references(() => categories.id, { onDelete: "restrict" }),
    name: text("name").notNull(),
    nameZh: text("name_zh"),
    origin: text("origin").notNull(),
    description: text("description").notNull(),
    notes: text("notes").array().notNull().default(sql`'{}'::text[]`),
    priceCents: integer("price_cents").notNull(),
    unit: text("unit").notNull(),
    badge: productBadge("badge"),
    details: jsonb("details").$type<{ term: string; detail: string }[]>().notNull().default([]),
    /** Gongfu brewing parameters; teas only. */
    brew: jsonb("brew").$type<{ leaf: string; water: string; time: string; infusions: string }>(),
    imageUrl: text("image_url").notNull(),
    imageAlt: text("image_alt").notNull(),
    gallery: jsonb("gallery").$type<{ src: string; alt: string }[]>().notNull().default([]),
    ...timestamps,
  },
  (t) => [
    index("products_category_id_idx").on(t.categoryId),
    check("products_price_cents_nonnegative", sql`${t.priceCents} >= 0`),
  ],
);

// Kept apart from `products` because it changes often (and orders will decrement it later).
export const productStock = pgTable(
  "product_stock",
  {
    productId: integer("product_id")
      .primaryKey()
      .references(() => products.id, { onDelete: "cascade" }),
    quantity: integer("quantity").notNull().default(0),
    /** Shown when sold out, e.g. when the next harvest arrives. */
    restockNote: text("restock_note"),
    updatedAt: timestamps.updatedAt,
  },
  (t) => [check("product_stock_quantity_nonnegative", sql`${t.quantity} >= 0`)],
);

export const orderStatus = pgEnum("order_status", ["pending", "paid", "failed", "expired"]);

// Created as `pending` when checkout starts, in the same batch that reserves the
// stock. Only Stripe (webhook or a server-side session lookup) moves it to
// `paid`; `failed`/`expired` give the reserved stock back (see `lib/orders.ts`).
export const orders = pgTable(
  "orders",
  {
    // Generated in the app so the order, its items and the stock update fit in one db.batch().
    id: uuid("id").primaryKey(),
    userId: text("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "restrict" }),
    status: orderStatus("status").notNull().default("pending"),
    currency: text("currency").notNull().default("usd"),
    /** From our prices when checkout started; Stripe must charge exactly this. */
    subtotalCents: integer("subtotal_cents").notNull(),
    /** What Stripe reports as charged, once paid. */
    amountTotalCents: integer("amount_total_cents"),
    email: text("email"),
    shippingAddress: jsonb("shipping_address").$type<{
      name: string;
      address: {
        line1: string | null;
        line2: string | null;
        city: string | null;
        state: string | null;
        postal_code: string | null;
        country: string | null;
      };
    }>(),
    stripeCheckoutSessionId: text("stripe_checkout_session_id").unique(),
    stripePaymentIntentId: text("stripe_payment_intent_id").unique(),
    paidAt: timestamp("paid_at", { withTimezone: true }),
    ...timestamps,
  },
  (t) => [
    index("orders_user_id_idx").on(t.userId),
    check("orders_subtotal_cents_nonnegative", sql`${t.subtotalCents} >= 0`),
  ],
);

/** Name and price are snapshots, so later catalog edits don't rewrite past orders. */
export const orderItems = pgTable(
  "order_items",
  {
    orderId: uuid("order_id")
      .notNull()
      .references(() => orders.id, { onDelete: "cascade" }),
    productId: integer("product_id")
      .notNull()
      .references(() => products.id, { onDelete: "restrict" }),
    name: text("name").notNull(),
    unitPriceCents: integer("unit_price_cents").notNull(),
    quantity: integer("quantity").notNull(),
  },
  (t) => [
    primaryKey({ columns: [t.orderId, t.productId] }),
    check("order_items_quantity_positive", sql`${t.quantity} > 0`),
  ],
);

export const categoriesRelations = relations(categories, ({ many }) => ({
  products: many(products),
}));

export const productsRelations = relations(products, ({ one }) => ({
  category: one(categories, { fields: [products.categoryId], references: [categories.id] }),
  stock: one(productStock),
}));

export const productStockRelations = relations(productStock, ({ one }) => ({
  product: one(products, { fields: [productStock.productId], references: [products.id] }),
}));

export const ordersRelations = relations(orders, ({ one, many }) => ({
  user: one(user, { fields: [orders.userId], references: [user.id] }),
  items: many(orderItems),
}));

export const orderItemsRelations = relations(orderItems, ({ one }) => ({
  order: one(orders, { fields: [orderItems.orderId], references: [orders.id] }),
  product: one(products, { fields: [orderItems.productId], references: [products.id] }),
}));

export * from "./auth-schema";
